### ISSUE TITLE
서버를 구축한다.

### ISSUE THREAD

**Issue by sonrose** [selab-hs/glass-bottle#12]
### 👥 작업에 참여한 인원

@sonrose

### 📑 작업 사항

AWS로 서버를 구축한다.

**Comment by DongGeon0908** [comment]
- DB Setup
- Redis Setup 

2개가 선행되어야 될 것 같아요,.

**Comment by sonrose** [comment]
반영하여 수정하였습니다.

**Comment by InJun2** [comment]
처리되었습니다
