### ISSUE TITLE
편지 단일 발송 기능

### ISSUE THREAD

**Issue by HwangHarim** [selab-hs/glass-bottle#75]
### 👥 작업에 참여한 인원

@sonrose 

### 📑 작업 사항

- 편지를 단일 user에게 보낼 수 있다.
- 예외 처리(제목 길이, 내용 길이)

### 📋 이슈 혹은 고려할 점

- 발신자는 수신자의 정보를 알고 있다.
- 수신자도 편지의 발신자 정보를 알고 있다.

**Comment by InJun2** [comment]
해당 기능은 취소하고 랜덤 mbti 답변 기능 구현 예정
