### ISSUE TITLE
편지 전송 기능을 구현한다.

### ISSUE THREAD

**Issue by sonrose** [selab-hs/glass-bottle#8]
### 👥 작업에 참여한 인원

@sonrose 

### 📑 작업 사항

대상 설정 없이 편지 전송하는 기능을 만든다.

*유리병 편지 느낌: 아래 이미지 참조
![KakaoTalk_Photo_2023-05-30-15-44-08 001](https://github.com/selab-hs/glass-bottle/assets/71416769/b3fb7eac-6250-4be4-b66b-64ee40ca2695)
![KakaoTalk_Photo_2023-05-30-15-44-09 002](https://github.com/selab-hs/glass-bottle/assets/71416769/1c431ef5-a3c3-47e5-be89-48d69b382549)

*참고 자료
https://dpg.danawa.com/mobile/news/view?boardSeq=60&listSeq=1739086&logger_kw=dpgshare_url&share=directurl

### 📋 이슈 혹은 고려할 점

추후 추가해야 할 기능 (대상 설정)
1. 내가 답장 받고 싶은 MBTI를 설정하여 해당 유저에게만 편지가 가도록 전송
2. 전체 유저에게 편지 전송

**Comment by DongGeon0908** [comment]
편지라는게 정확히 어떤 매체인지 구체화해주세요
